### ISSUE TITLE
Add mobile layout

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#100]
Page looks ugly on mobile browsers

![image](https://user-images.githubusercontent.com/7374733/50004628-0e0b2480-ffa8-11e8-8acb-92e4c26e2078.png)
![image](https://user-images.githubusercontent.com/7374733/50004634-12374200-ffa8-11e8-9b7a-145af364d945.png)

**Comment by marwin1991** [comment]
https://mobile.ant.design/docs/react/introduce

**Comment by marwin1991** [comment]
Some changes are availbe at https://libamtrack.github.io/web_dev/
- Main page looks really nice at mobile phone browsers
- In function view side menu is hidden automaticly when browser width is below lg: ('992px')

still working at plot view

**Comment by grzanka** [comment]
Main page looks really nice - I confirm !

**Comment by grzanka** [comment]
I consider it fixed in PR #157
