### ISSUE TITLE
Notes should appear on the chart (not axis)

### ISSUE THREAD

**Issue by KingaJelen** [libamtrack/web#103]
![przechwytywanie](https://user-images.githubusercontent.com/33397810/50163398-a541e600-02e0-11e9-92e8-31b79a451e0d.PNG)

**Comment by marwin1991** [comment]
I've noticed that when you change y-axis to linear and then back to log it is okay, now when you will add new data series again error appears.

**Comment by adudzik** [comment]
> I've noticed that when you change y-axis to linear and then back to log it is okay, now when you will add new data series again error appears.

Zoom in and zoom out also helps. Looks like this is plotly.js problem, because it's built-in feature - we don't manage it.

**Comment by grzanka** [comment]
@adudzik if this is a plotly bug, can't we file an issue to plotly developers ?

**Comment by adudzik** [comment]
Could you test it again? I merged the newest release of plotly.js and issue described by @marwin1991 and @KingaJelen might be fixed.

On [web](https://libamtrack.github.io/web/#Particlerangeandstoppingpower/CSDArangeofproton/ion) for default values works fine.

On [web_dev](https://libamtrack.github.io/web_dev/#Particlerangeandstoppingpower/CSDArangeofproton/ion) there is still older version and for defaults that issue exists.

**Comment by KingaJelen** [comment]
That's ok now.
