### ISSUE TITLE
Should use another name ... 

### ISSUE THREAD

**Issue by KingaJelen** [libamtrack/web#104]
"Points" is an improper  naming.
![przechwytywanie](https://user-images.githubusercontent.com/33397810/50163747-68c2ba00-02e1-11e9-95c6-f435b3a680d2.PNG)

**Comment by adudzik** [comment]
> "Points" is an improper naming.

"Points" specifies that this plot is created from 44 points between 0.1 and 500.

I forgot to add in JSON config file button for changing plot type. When it's not set the default value is lines. I will fix it.

**Comment by adudzik** [comment]
Button was added. It should works correct now. If not, please reopen.

**Comment by KingaJelen** [comment]
I mean, this name is misleading :)
