### ISSUE TITLE
Should be the numerical range or the suggested minimum value

### ISSUE THREAD

**Issue by KingaJelen** [libamtrack/web#111]
![przechwytywanie](https://user-images.githubusercontent.com/33397810/50165319-fe137d80-02e4-11e9-8bff-9ddae76846ab.PNG)

**Comment by marwin1991** [comment]
what function is it?

**Comment by adudzik** [comment]
@marwin1991 I think it will be good to add some information to every function.

**Comment by marwin1991** [comment]
@adudzik  like what it do and what are corrent values?

**Comment by adudzik** [comment]
Changed for single input in #146. 
Entry_module require more work. Will be done with #90 .

**Comment by grzanka** [comment]
Seems fixed now
