### ISSUE TITLE
CSDA calculation: provide more significant figures and total energy

### ISSUE THREAD

**Issue by jbrage** [libamtrack/web#1135]
Would it be possible to 
1) select the energy either as MeV or MeV/u? 
2) provide at least 3-4 significant figures for the range?

![image](https://github.com/user-attachments/assets/64a4414f-0b17-4fca-bedd-f9a1ede9a69e)

**Comment by grzanka** [comment]
@jbrage I've improved a bit the calculator, check it again at:
https://libamtrack.github.io/web_dev/#Calculators/CSDArange

once you are happy, I will propagate the changed to https://libamtrack.github.io/web/ as well

By the way - do you have some good suggestion on the default values of all the text fields and on the description ?

<img width="769" alt="Screenshot 2024-08-20 at 14 24 59" src="https://github.com/user-attachments/assets/87786ac9-1724-417d-a36b-36ac53860bc5">
<img width="726" alt="Screenshot 2024-08-20 at 14 25 16" src="https://github.com/user-attachments/assets/18fd703e-9fbd-47c4-9d3e-e5ca341818c5">

**Comment by grzanka** [comment]
Do you think similar changes should be applied here ?
https://libamtrack.github.io/web_dev/#Particlerangeandstoppingpower/CSDArangevsenergy
