### ISSUE TITLE
Move "Plot as Points/Line" to "More plot options"

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#145]
**Points** in "Plot as Points/Line" may be easily confused with "Generate XXX **Points**"

From my experience I find myself changing axis from linear to logarithmic than changing "Plot as" option. Consider moving "Plots as Points/Line" to "More plot options" and moving "Change axis type" to always visible place (out of "More plot options")

**Comment by grzanka** [comment]
I like this idea !

Can you also keep "More plot options" always expanded or move "log/linear" stuff to more visible place ?

**Comment by adudzik** [comment]
Done in #146
