### ISSUE TITLE
Status of wasm file in currently deployed library

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#161]
I was trying to set "start" value of energy range to zero in 
https://libamtrack.github.io/web/#EnergyAndMomentum/Relativistic%CE%B2fromenergy
using master branch and commit 0a3a7e2.

It gave me following error:
![image](https://user-images.githubusercontent.com/7374733/51162109-51053400-1895-11e9-8af5-f487883827db.png)

When looking at forjs branch in core library the corresponding assert seems to be fixed:
![image](https://user-images.githubusercontent.com/7374733/51162142-6da16c00-1895-11e9-998f-264f227d96b3.png)

What is the status of wasm and js files in currently deployed library ?

**Comment by marwin1991** [comment]
https://libamtrack.github.io/web_dev/#EnergyAndMomentum/Relativistic%CE%B2fromenergy

can you test it there because I don't now how you put 0 there because I get filed validation error.
There is the newst compiled library.

**Comment by grzanka** [comment]
I was testing it locally with a bit different validation range. It works well now, feel free to merge.
