### ISSUE TITLE
Static plots on mobile devices

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#166]
When scrolling libamtrack web page https://libamtrack.github.io/web/ on mobile devices with touchscreen (i.e. smartphone) users accidentally press on the area of the plotly graph. When trying to swipe over it the page doesn't scroll, but the interactions with plots are possible.

I'd recommend to include only static plots (images) for mobile devices, maybe with some action (double click) to activate interactive one (with zooming etc) and some other action to deactivate interactive mode and bring back normal behavior of swipe - scrolling the page.

**Comment by marwin1991** [comment]
I will look how plotly.js supports it, I also encourted this problem

**Comment by grzanka** [comment]
The problem sound similar to embedding google maps in mobile webpages - how is it solved there ?

**Comment by marwin1991** [comment]
https://github.com/plotly/plotly.js/issues/2844
