### ISSUE TITLE
Check w3c validation results

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#191]
https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Flibamtrack.github.io%2Fweb

It looks that `<SCRIPT>` section is ill-placed

![image](https://user-images.githubusercontent.com/7374733/52055851-da3c8c00-2560-11e9-8eac-9f3ce046b5c1.png)

**Comment by marwin1991** [comment]
should be okay now
