### ISSUE TITLE
Proton-therapy analytical models as first category

### ISSUE THREAD

**Issue by marwin1991** [libamtrack/web#261]
If we put categoris in this order 
Proton-therapy analytical models
Particle range and stopping power
Energy And Momentum
Calculators
Track Structure

we will use more first page workspace for screens that can handle for categories in a row, because
Track Structure will be under Proton-therapy analytical models and both of then are short so they will display without need of scrolling

**Comment by grzanka** [comment]
Calculators are separate item which should be reflected by the order on the page, apart from that reordering looks as good idea
