### ISSUE TITLE
CSDA Range of proton or ion - final energy = 0

### ISSUE THREAD

**Issue by Vojtone** [libamtrack/web#304]
While working on #301 I've found bug at: https://libamtrack.github.io/web/#Particlerangeandstoppingpower/CSDArangeofproton/ion.

Scenario:
1. Submit the form with default values (final energy = 0)
2. Change final energy and submit the form
3. Change final energy back to 0 and submit the form <- error occurs
![image](https://user-images.githubusercontent.com/32063111/56155088-5e2bdf00-5fba-11e9-89a3-2703f5d9340f.png)
![image](https://user-images.githubusercontent.com/32063111/56155160-8ca9ba00-5fba-11e9-98fb-fc99f998cc07.png)

Shouldn't be final energy > 0?

**Comment by grzanka** [comment]
Final energy should be smaller than start energy.

Imagine a particle which is slowing down from some kinetic energy E_kin down to E_final.
We are interesting in plotting a range (think of it as "braking distance") as a function of different starting energies (including E_kin = 0, which means being at rest). As long as E_final is zero it is pretty simple.

Also as long as these different initial kinetic energies  E_kin are larger than E_final everything is also fine. But keeping the lower plot limit (lowest possible E_kin) at zero and increasing E_final to some value creates an unphysical condition for which there is no error check in C backend.

**Comment by Vojtone** [comment]
Therefore I suggest changing default parameters. Right now both final energy and start energy equals 0.
