### ISSUE TITLE
multiple issues

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#35]
Here is a very dirty list of tasks and things to correct, quickly written in the plane. Feel free to migrate them to separate issues

1. METHODS TO IMPLEMENT

- [x] range (AT_CSDA_range_g_cm2_multi / AT_CSDA_range_g_cm2_single)
- [x] energy after slab (AT_CSDA_energy_after_slab_E_MeV_u_single / AT_CSDA_energy_after_slab_E_MeV_u_multi)

2. PROBLEMS

Beta From Energy Single
- [x] Setting Energy to 0,1 (or some string) gives error "MESSAGE TO DEVELOPER: NO PARAMETER E_MeV_u IN OBJECT PASSED TO THIS FUNCTIONS" it is very misleading, same for negative numbers.
- [x] TODO: add Energy units there
- [x] I wouldn't expect that users will type energy from range outside [1e-3, 1e3] thus printing 4 digits after . should be enough
- [x] Setting energy to 0 should give beta=0, it gives an error now.
- [x] Setting energy to negative number gives white page.

Beta From Energy
- [x] By default we should  have energy range 0..300 and 300 points instead of step.
- [x] Switching from "Line" to "Points" should not generate new line serie.

"Energy From Beta Single" 
- [x] setting Beta to 1 gives white page.
- [x] Displaing 3 significat digits should be enough

"Energy From Beta" 
- [x] start point at 0 should be allowed, by default we should have 300 points for beta between 0 and 0.8
- [x] On horizonta axis energy units should be displayed.

"Energy Of Particle With Given Momentum Single" 
- [x] default momentum should be 300

"Energy Of Particle With Given Momentum" 
- [x] start 0, end 500, 500 points

"Relativistic Momentum Per Nucleon Of Particle Single" 
- [x] default energy: 150

"Relativistic Momentum Per Nucleon Of Particle" 
- [x] should allow start at 0, end should be 300, and 300 points, 

"Relativistic Momentum Per Nucleon Of Particle":
- [x]  start at 0.001, end at 10 MeV, plot as Line
- [x]  500 points forming "geometrical" ! series
- [x]  by default log scale on X and Y axis
 
 "Maximum Electron Range Single"
 - [x]  by default energy 0.01 MeV
 - [x]  output units should be m, not MeV - to check
  
  "Mass stopping power with no"
  - [x]  start at 0.01, end at 500 MeV
  - [x]  500 points forming "geometrical" ! series
  - [x]  by default log scale on X and Y axis
  - [x]  default source: PSTAR
    
  "Effective Charge From Beta Barkas-Bethe Single"
 - [x]  by default: carbon ion
 - [x]  beta 0.1
 - [x]  no output units
   
   "Effective Charge From Beta Barkas-Bethe"
 - [x]  by default proton
- [x]  start at 0, end at 0.6, 500 points forming geometrical series
  - [x]  by default logarithmic scale on X, linear scale on Y

    "Effective Charge From Energy Barkas-Bethe Single"
  - [x]   energy: 10
  - [x]   particle: C
  - [x]   no output units
  - [x]   energy units: "MeV/amu"
    
    "Effective Charge From Beta Barkas-Bethe"
  - [x]   start 0.01, end 100, 500 points forming geometrical series
  - [x]   no output units
  - [x]   by default logarithmic scale on X, linear scale on Y
  - [x]   energy units: "MeV/amu", not "MeV"

**Comment by marwin1991** [comment]
Beta from Energy Single
- Setting energy to 0 should give beta=0, it gives an error now.
[AT_PhysicsRoutines.c](https://github.com/libamtrack/library/blob/master/src/AT_PhysicsRoutines.c)

there is a line `assert( E_MeV_u > 0.);`  so it is not possible

**Comment by adudzik** [comment]
> "Relativistic Momentum Per Nucleon Of Particle"
>  -[ ] should allow start at 0, end should be 300, and 300 points,
> "Relativistic Momentum Per Nucleon Of Particle":

There is duplicate description. I assume, that this second list is correct.

**Comment by grzanka** [comment]
> Beta from Energy Single
> 
> * Setting energy to 0 should give beta=0, it gives an error now.
>   [AT_PhysicsRoutines.c](https://github.com/libamtrack/library/blob/master/src/AT_PhysicsRoutines.c)
> 
> there is a line `assert( E_MeV_u > 0.);` so it is not possible

OK, so it should be fixed in libamtrack core itself.

**Comment by grzanka** [comment]
> > "Relativistic Momentum Per Nucleon Of Particle"
> > -[ ] should allow start at 0, end should be 300, and 300 points,
> > "Relativistic Momentum Per Nucleon Of Particle":
> 
> There is duplicate description. I assume, that this second list is correct.

Yes :)

**Comment by marwin1991** [comment]
To use proton we should use H(1001) or add new particle Proton(1000) ?

**Comment by grzanka** [comment]
We use 1001, but better to name it `proton` than `H`

**Comment by grzanka** [comment]
> > OK, so it should be fixed in libamtrack core itself.
> 
> Should we create an issue for that in [library repo](https://github.com/libamtrack/library)?

Yes !

**Comment by adudzik** [comment]
> Yes !

Done in [#16](https://github.com/libamtrack/library/issues/16)

**Comment by grzanka** [comment]
@adudzik @marwin1991 there are few new fixes in libamtrack. I'd like to make myself a new `*wasm` file. What should I do ? Is there any documentation describing such process ?

**Comment by marwin1991** [comment]
@adudzik what is the status?

**Comment by grzanka** [comment]
Missing one moved to 164
