### ISSUE TITLE
Unneeded change of axis scale when switching points->lines

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#36]
To reproduce go to:
https://libamtrack.github.io/web/#StoppingPower/Massstoppingpower

Axis scales are log-log

Before clicking on "Submit" click button Plot as "Line".

Axis are changing to lin-lin - why ?

**Comment by adudzik** [comment]
I added option to allow users to define default scale for axis today. It looks like I don't keep them in some place becaues "lines" is plotly.js default scale (when we don't provide ours). I think it's quick fix.
