### ISSUE TITLE
Fix RDD plots

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#57]
Please investigate https://libamtrack.github.io/web/#TrackStructure/RadialDoseDistribution ?

It looks that all the needed numbers are in the JSON file, but still this is not reflected in UI:
 - default log-log plot

**Comment by adudzik** [comment]
This situation occurs because I've created another branch in #56 (before @marwin1991 merged Your PR and my branch has not this changes). I've named it feature/..., so it was deployed on GH Pages. I triggered redeploy master version, it should works fine.

**Comment by grzanka** [comment]
What do you think of deploying feature to some other location ? Like another repo with github pages ?

**Comment by marwin1991** [comment]
I think it is good idea. You can create repo webTest or webDev in libamtrack organizations

**Comment by grzanka** [comment]
https://github.com/libamtrack/web_dev please test

**Comment by marwin1991** [comment]
Changes should be avaliable at https://libamtrack.github.io/web_dev/

**Comment by grzanka** [comment]
Thanks !
