### ISSUE TITLE
Improve autogenerated text/data files to download

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#59]
Right now files with data ("Download" option) are bit tricky to digest:

![image](https://user-images.githubusercontent.com/7374733/49386545-151c7200-f720-11e8-827d-0e82c79ba59d.png)

I propose to:
- [ ] remove `#haha` line
- [ ] add comment line mentioning that the file was generated with libamtrack
- [ ] add comment line with the time the file was generated
- [ ] strip `"` from fields with numerical data: `0.1,0.014651766707559846` instead of `"0.1","0.014651766707559846"`

What do you think of saving multiple series in many-columns format, instead of appending the data below ?

**Comment by adudzik** [comment]
> remove #haha line

Sorry about that, it was for debugging, i forgot to remove it :)

> What do you think of saving multiple series in many-columns format, instead of appending the data below ?

Do you mean something like that: 
x1, F(x1), x2, F(x2), ....
x1, F(x1), x2, F(x2), ....
or 
x1, x2, ..., F(x1), F(x2), ...
x1, x2, ..., F(x1), F(x2), ...

**Comment by adudzik** [comment]
After some changes:

![image](https://user-images.githubusercontent.com/23633694/49647800-fe2d9680-fa23-11e8-861a-8d60464c5669.png)

I'm still a bit confused about how it should displays when some series has more values than other ones.
In above example I had respectively 5, 8 and 3 points. For now I used `,` without values between.

@grzanka Is it okay?

**Comment by grzanka** [comment]
Could you attach such a file ? I'd like to test it.

**Comment by adudzik** [comment]
[test4.txt](https://github.com/libamtrack/web/files/2658672/test4.txt)

I hope it's well formatted beacuse GitHub does not support attaching CSV files, so I save CSV as TXT.

**Comment by grzanka** [comment]
Works well: 
![image](https://user-images.githubusercontent.com/7374733/49671302-b7619000-fa67-11e8-8611-100c645bcd1c.png)
