### ISSUE TITLE
remove obsolete files from functionsFromC

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#6]

**Comment by marwin1991** [comment]
Done in #10

**Comment by grzanka** [comment]
Where exactly ?

**Comment by adudzik** [comment]
In this commit [link](https://github.com/libamtrack/web/pull/10/commits/be71731e74acc5068c8135ea5dc46f1d9ad0918c) I removed not used files with materials and particles.

**Comment by grzanka** [comment]
OK, got it
