### ISSUE TITLE
new validator options

### ISSUE THREAD

**Issue by marwin1991** [libamtrack/web#70]
Many configuration files have validators for input. 

1. Can we provide value like 10e10 or maybe 10^10 ? 
2. Some cases should not have limit? Like energy can be infinity, but we know that numbers in computers cant. Will it cause overflow?( i will create new issue to investigate it ). So i was wondering about validator like: >0, so it accept everything greater than 0.  

I think is not important issue, but leave it for future.

**Comment by adudzik** [comment]
> Can we provide value like 10e10 or maybe 10^10 ?

Yes, we can -> 1e3 will be interpreted as 1000.
