### ISSUE TITLE
Migrate cToJsFunctionsGenerator from marwin1991 GH pages to libamtrack GH pages

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#84]
https://marwin1991.github.io/cToJsFunctionsGenerator/

**Comment by marwin1991** [comment]
I thought that this "generator" does not have anything in common with libamtrack so I used my personal repository. If you think that it should be here, please create repository, you can also pick a better name for this project.

**Comment by grzanka** [comment]
Is it possible to serve GH pages from https://github.com/libamtrack/web_dev, but from branch other than `gh-pages` ? I was thinking of putting it there. 
If you think that better idea is to have new repo - I'll create it.

**Comment by marwin1991** [comment]
But there can be only one gh-pages per repo. I think there should be new repository.

**Comment by grzanka** [comment]
Done https://github.com/libamtrack/c2JsGenerator

**Comment by marwin1991** [comment]
I think we will use c@JsGenerator's repo to create issues etc. This one i am closing.
