### ISSUE TITLE
Replace electron energy with ion energy (wmax) in track width

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#98]

**Comment by marwin1991** [comment]
Can you get more information about it?
Do you mean this function? https://libamtrack.github.io/web/#Calculators/Electronrange

**Comment by grzanka** [comment]
Right now we have "electron energy" on X axis and "electron range" on Y axis.
In fact we are mostly interested in electrons (so called delta electrons https://pl.wikipedia.org/wiki/Elektron_delta , https://en.wikipedia.org/wiki/Delta_ray) created by protons/ions of some energy. 
User knows what is the ion/proton energy and wants to know how far from the ion track the electron can travel (its range).
There is a formula which allows to calculate (maximum) electron energy if you know proton/ion energy, i.e. `AT_max_E_transfer_MeV`.

I'd imagine doing these two steps purely in javascript:
 - calculating max electron energy
 - calculate electron range

**Comment by grzanka** [comment]
It looks that the energy was already specified as ion energy, not as electron energy.

The results 

![newplot](https://user-images.githubusercontent.com/7374733/50481462-ecfff600-09e1-11e9-8cae-42a9b01ae726.png)

seems to be consistent with results published in https://arxiv.org/pdf/1410.1378.pdf
![image](https://user-images.githubusercontent.com/7374733/50481383-7d8a0680-09e1-11e9-80aa-41eade1262e3.png)

and in Wayne D Newhauser and Rui Zhang 2015 Phys. Med. Biol. 60 R155
http://iopscience.iop.org/article/10.1088/0031-9155/60/8/R155#pmb505403s2-1
> Even for very energetic protons, the secondary electrons do not acquire enough energy to travel more than a few millimeters from the proton track. For example, at 200 MeV proton energy, the maximum secondary electron energy is around 500 keV, which corresponds to an electron range of approximately 2 mm in water.
