### ISSUE TITLE
Energy decrease after slab is crashing

### ISSUE THREAD

**Issue by grzanka** [libamtrack/web#99]
when material other than liquid water is choosen

![image](https://user-images.githubusercontent.com/7374733/50003515-2c6f2100-ffa4-11e8-935d-e5e774af4489.png)

**Comment by adudzik** [comment]
Yes, I wanted to mention this. This situation occurs because library returns error and closes itself. We can add exception handlers in JS wrapper function for that but what should be displayed for the users?

**Comment by adudzik** [comment]
It's connected with issue #76.

**Comment by grzanka** [comment]
In case error is known we should display the error message (i.e. content of stderr stream from libamtrack, or some error code, together with summary of function signature + values of  parameters). If the error is unknown, some nice modal should be displayed, like "Unknown error, consider choosing other input parameters"
